on: [push]

jobs:
  compile_exercises_job:
    runs-on: ubuntu-latest
    name: Compile specification
    steps:
    - uses: actions/checkout@v2
    - name: Prepare template
      run: |
        sed -i "s/-SNAPSHOT/-SNAPSHOT (`git rev-parse --short HEAD`)/" ldbc.cls
    - name: Build PDFs with the LaTeX engine in Docker
      uses: ldbc/document-builder@main
      with:
        makefile-arguments: texfot compile_query_cards workloads
    - name: Create package
      run: |
          mkdir out/
          cp -r .circleci out/
          cp *.pdf out/
          cp standalone-query-cards/*.pdf out/
          cp figures/schema-comfortable.pdf out/schema.pdf
          cp figures/schema-comfortable.png out/schema.png
          cp figures/example-graph-with-refreshes.pdf out/example-graph-with-refreshes.pdf
          cp figures/example-graph-without-refreshes.pdf out/example-graph-without-refreshes.pdf
          cp deployment/readme-to-deploy.md out/README.md
    - name: Deploy site and PDFs
      uses: maxheld83/ghpages@68f783a4f5313d776c1599e18479607e71c9c738  # v0.3.0
      env:
        BUILD_DIR: out/
        GH_PAT: x-access-token:${{ secrets.GITHUB_TOKEN }}
      # https://github.com/marketplace/actions/twitter-together#setup
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif
      # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
